### ISSUE TITLE
ValueError: You selected an invalid strategy name: `strategy='dp'`

### ISSUE THREAD

**Issue by Tylersuard** [RuslanKhalitov/ChordMixer#2]
Traceback (most recent call last):
  File "/content/ChordMixer/trainer.py", line 394, in cli_main
    trainer = Trainer(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 393, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 140, in __init__
    self._check_config_and_set_final_flags(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 209, in _check_config_and_set_final_flags
    raise ValueError(
ValueError: You selected an invalid strategy name: `strategy='dp'`. It must be either a string or an instance of `pytorch_lightning.strategies.Strategy`. Example choices: auto, ddp, ddp_spawn, deepspeed, ... Find a complete list of options in our documentation at https://lightning.ai/

**Comment by RuslanKhalitov** [comment]
Hi, this happens when using the new version of pytroch_lightning. Please use pytorch-lightning==1.9.0

**Comment by Tylersuard** [comment]
Thank you for your help.  I was able to get this up and running using a Google Colab notebook: https://colab.research.google.com/drive/1Kpa43G5UUoWnTakEwgr6D64I2HzozUKf?usp=sharing
