### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'train_dataloader'

### ISSUE THREAD

**Issue by Tylersuard** [RuslanKhalitov/ChordMixer#3]
Traceback (most recent call last):
  File "/content/ChordMixer/trainer.py", line 411, in cli_main
    trainer.fit(model, datamodule=dm)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 92, in launch
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 911, in _run
    self.strategy.setup(self)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/strategies/ddp.py", line 166, in setup
    self.setup_optimizers(trainer)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/strategies/strategy.py", line 138, in setup_optimizers
    self.optimizers, self.lr_scheduler_configs = _init_optimizers_and_lr_schedulers(self.lightning_module)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/optimizer.py", line 171, in _init_optimizers_and_lr_schedulers
    optim_conf = call._call_lightning_module_hook(model.trainer, "configure_optimizers", pl_module=model)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 142, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/content/ChordMixer/trainer.py", line 125, in configure_optimizers
    num_training_steps=self.total_steps()
  File "/content/ChordMixer/trainer.py", line 106, in total_steps
    l = len(self.trainer.datamodule.train_dataloader())
AttributeError: 'NoneType' object has no attribute 'train_dataloader'

**Comment by RuslanKhalitov** [comment]
This error suggests there is an error with data loader initialization. Most probably, this happens because of the packages mismatch. Please make sure the versions are the same as in the requirements.txt.

**Comment by Tylersuard** [comment]
Thank you.  As a side note, thank you for publishing this repo.  The ChordMixer is a great idea.  Increasing the context length of LLMs is SO important, congratulations on achieving SOTA.
